"""Initial migration.

Revision ID: 57b703eb7a0a
Revises: 
Create Date: 2023-04-09 00:39:00.785036

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '57b703eb7a0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IPCountry', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True))
        batch_op.add_column(sa.Column('ConnectingIP', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ConnectingIP')
        batch_op.drop_column('IPCountry')

    # ### end Alembic commands ###
